name: dagger

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dagger
        run: curl -L https://dl.dagger.io/dagger/install.sh | sh
      - name: Run tests
        run: |
          ./bin/dagger run node ci/index.js
