name: dagger

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
      - name: Install dependencies
        run: |
          yarn install
      -
        name: Dagger
        run: curl -L https://dl.dagger.io/dagger/install.sh | sh
      - name: Run tests
        run: |
          ./bin/dagger run node --loader ts-node ci/index.ts
